name: tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Bootstrap poetry
        run: pipx install poetry

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: poetry install

      - name: Run black formatting
        uses: psf/black@stable
        with:
            options: "--check --verbose"
            src: "google_books/ tests/"

      - name: Run flake8 linting
        uses: py-actions/flake8@v2
        with:
          max-line-length: 88
          ignore: "tests/*: E501, W503"

      - name: Run tests
        run: poetry run pytest -v --cov=google_books/

      - name: Send report to Coveralls
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel: true
          flag-name: Unit Test
          github-token: ${{ secrets.GITHUB_TOKEN}}

  coveralls_finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls finished
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel-finished: true